---
- name: BIG-IP SETUP
  hosts: lb
  connection: local
  gather_facts: false
  vars_files:
    - ./vars/default_vars.yml
    - ./credentials/f5_credentials.yml
  vars:
    pool_name: http_pool
    vip_name: vip

  tasks:

  - name: ADD VIRTUAL SERVER
    bigip_virtual_server:
      provider:
        server: "{{ ansible_host }}"
        user: "{{ F5_USERNAME }}"
        password: "{{ F5_PASSWORD }}"
        server_port: "8443"
        validate_certs: "no"
      name: "{{ vip_name }}"
      destination: "{{ ansible_host }}"
      port: "443"
      enabled_vlans: "all"
      all_profiles: ['http','clientssl','oneconnect']
      pool: "{{ pool_name }}"
      snat: "Automap"
