---
- name: Create SSL profile on BIG-IP
  hosts: lb
  connection: local
  gather_facts: false
  vars_files:
    - ./vars/default_vars.yml
    - ./credentials/f5_credentials.yml
  vars:
    cert_name: tower_cert
    key_name: tower_key
    profile_name: tower_ssl_profile

  tasks:

  - name: Create a client SSL profile with a cert/key setting
    bigip_profile_client_ssl:
      name: "{{ profile_name }}"
      state: present
      cert_key_chain:
      - cert: "{{ cert_name }}"
        key: "{{ key_name }}"
      provider:
        server: "{{ ansible_host }}"
        user: "{{ F5_USERNAME }}"
        password: "{{ F5_PASSWORD }}"
        server_port: "8443"
        validate_certs: "no"
